name: Daily Web Visitor

on:
  schedule:
    # 매일 오전 9시 (UTC 00:00 = 한국시간 09:00)에 실행
    - cron: '0 0 * * *'
  workflow_dispatch: # 수동 실행 가능

jobs:
  visit-website:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run web visitor script
      run: |
        python web_visitor.py
