name: Daily Web Visitor

on:
  schedule:
    - cron: '0 0 * * *'  # 매일 오전 9시 (한국시간)
  workflow_dispatch:

jobs:
  visit-website:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    - run: pip install requests
    - run: python web_visitor.py
      env:
        TARGET_URLS: ${{ secrets.TARGET_URLS }}
